### Register User
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "username": "userbaru",
  "password": "passwordku"
}

### Login User
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "username": "userbaru",
  "password": "passwordku"
}
